AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3] # as per VGG 16 model ,will vary as per the model
BATCH_SIZE: 16
INCLUDE_TOP: False # because we have not taken top part as my base model
EPOCHS: 3
CLASSES: 2
WEIGHTS: imagenet
LEARNING_RATE: 0.01